/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AuthModal: typeof import('./../src/components/Auth/AuthModal.vue')['default']
    CommentItem: typeof import('./../src/components/CommentItem/index.vue')['default']
    Drawer: typeof import('./../src/components/Drawer/Drawer.vue')['default']
    Header: typeof import('./../src/components/layout/Header/index.vue')['default']
    Layout: typeof import('./../src/components/layout/index.vue')['default']
    PageComponent: typeof import('./../src/components/PageComponent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./../src/components/layout/Header/Switch.vue')['default']
    Tag: typeof import('./../src/components/Widget/Tag.vue')['default']
    Weather: typeof import('./../src/components/Widget/Weather.vue')['default']
  }
}
